[project]
name = "dwarf-p-ice3-dace"
requires-python = ">=3.10"
version = "0.0.0"
dependencies = [
    "dace>=1.0.2",
]

[build-system]
requires = [
  "uv_build>=0.7.19,<0.8.0",
]
build-backend = "uv_build"

[tool.uv.build-backend]
namespace = true

[tool.uv.workspace]
members = [
  "/home/maurinl/maurinl26/dwarf-p-ice3-dace",
]
